name: CI
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: mkdir ${{ github.workspace }}/../build
      - run: cd ${{ github.workspace }}/../build
      - run: cmake -S ${{ github.workspace }}
      - run: make
      - run: ctest
