name: CI
on: [push]

env:
  CMAKE_BUILD_DIR: ${{ github.workspace }}/builddir

jobs:

  Linux:
    runs-on: ubuntu-20.04
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/builddir
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure
        shell: bash
        run: |
          mkdir ${{ env.CMAKE_BUILD_DIR }}
          cmake -S ${{ github.workspace }} -B ${{ env.CMAKE_BUILD_DIR }}
      - name: Build
        shell: bash
        run: |
          cd ${{ env.CMAKE_BUILD_DIR }}
          make
      - name: Test
        shell: bash
        run: |
          cd ${{ env.CMAKE_BUILD_DIR }}
          ctest

  Windows:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Configure
        shell: powershell
        run: |
          new-item ${{ env.CMAKE_BUILD_DIR }} -itemtype directory
          cmake -S ${{ github.workspace }} -B ${{ env.CMAKE_BUILD_DIR }}
      - name: Build
        shell: powershell
        run: |
          Set-Location -Path ${{ env.CMAKE_BUILD_DIR }}
          make
      - name: Test
        shell: powershell
        run: |
          Set-Location -Path ${{ env.CMAKE_BUILD_DIR }}
          ctest
